CREATE TABLE recipes (
id INTEGER PRIMARY KEY AUTOINCREMENT,
description VARCHAR(200),
title TEXT NOT NULL,
body TEXT,
prep_time TEXT,
cooking_time TEXT,
ingredients TEXT,
instructions TEXT,
servings TEXT,
image_url TEXT,
slug TEXT UNIQUE,
difficulty TEXT,
dietary TEXT,
tags TEXT
);

-- Vegetarian, Vegan, Gluten-free
-- Beverage, Main Course, Appertiser, Dessert, Alcoholic, Side

INSERT INTO recipes (description, title, body, prep_time, cooking_time, ingredients, instructions, servings, image_url, slug, difficulty, dietary, tags)
VALUES
("Delicious spaghetti with marinara sauce", "Classic Spaghetti Marinara", "This classic spaghetti marinara recipe is perfect for a cozy night in. Made with simple ingredients, it's quick to prepare and bursting with flavor.", "20", "30", "Spaghetti noodles ~ Marinara sauce ~ Parmesan cheese ~ Fresh basil leaves", "1. Boil water in a large pot and cook spaghetti according to package instructions. ~ 2. Heat marinara sauce in a separate saucepan over medium heat. ~ 3. Drain spaghetti and toss with marinara sauce. ~ 4. Serve hot, garnished with grated Parmesan cheese and fresh basil leaves.", "4", "https://res.cloudinary.com/hksqkdlah/image/upload/SFS_Classic_Spaghetti_Marinara-17_c2urcq.jpg", "classic-spaghetti-marinara", "2", "", "Main Course"),
("Savory chicken and rice casserole", "Creamy Chicken and Rice Casserole", "This creamy chicken and rice casserole is a comforting dish that's perfect for a family dinner. With tender chicken, hearty rice, and a creamy sauce, it's sure to be a hit!", "15", "45", "Chicken breasts ~ Rice ~ Cream of chicken soup ~ Chicken broth ~ Frozen peas ~ Cheddar cheese ~ Bread crumbs", "1. Preheat oven to 350°F (175°C). ~ 2. Cook rice according to package instructions. ~ 3. In a large bowl, combine cooked chicken, cooked rice, cream of chicken soup, chicken broth, frozen peas, and shredded cheddar cheese. ~ 4. Transfer mixture to a greased baking dish. ~ 5. Sprinkle bread crumbs on top. ~ 6. Bake for 30 minutes, or until bubbly and golden brown.", "6", "https://www.foodiecrush.com/wp-content/uploads/2018/09/One-Pot-Chicken-and-Rice-Casserole-foodiecrush.com-025.jpg", "creamy-chicken-and-rice-casserole", "3", "", "Main Course"),
("Zesty lemon garlic shrimp pasta", "Lemon Garlic Shrimp Pasta", "This lemon garlic shrimp pasta is a refreshing and flavorful dish that's perfect for a summer dinner. With juicy shrimp, tangy lemon, and aromatic garlic, it's sure to impress!", "10", "20", "Shrimp ~ Linguine pasta ~ Garlic ~ Lemon ~ Cherry tomatoes ~ Fresh parsley ~ Olive oil ~ Salt ~ Black pepper", "1. Cook linguine pasta according to package instructions. ~ 2. In a large skillet, heat olive oil over medium heat. ~ 3. Add minced garlic and cook until fragrant. ~ 4. Add shrimp and cook until pink. ~ 5. Add halved cherry tomatoes, lemon juice, and zest. ~ 6. Toss cooked pasta with shrimp mixture. ~ 7. Season with salt, pepper, and chopped parsley. ~ 8. Serve hot.", "4", "https://img.buzzfeed.com/video-api-prod/assets/9ee2dadcbfcb4095872e6cdbaa24ff14/Thumb_A_FB.jpg", "lemon-garlic-shrimp-pasta", "4", "", "Main Course"),
("Hearty beef and vegetable stew", "Beef and Vegetable Stew", "This hearty beef and vegetable stew is a comforting meal that's perfect for chilly evenings. Packed with tender beef, hearty vegetables, and flavorful broth, it's sure to warm you up!", "20", "60", "Beef stew meat ~ Potatoes ~ Carrots ~ Celery ~ Onion ~ Garlic ~ Beef broth ~ Tomato paste ~ Worcestershire sauce ~ Bay leaves ~ Salt ~ Black pepper", "1. In a large pot, heat olive oil over medium-high heat. ~ 2. Add beef stew meat and brown on all sides. ~ 3. Add chopped onion and minced garlic. Cook until softened. ~ 4. Stir in tomato paste and cook for a few minutes. ~ 5. Add diced potatoes, carrots, and celery to the pot. ~ 6. Pour in beef broth and Worcestershire sauce. ~ 7. Add bay leaves and season with salt and pepper. ~ 8. Simmer for 45 minutes to 1 hour, until beef and vegetables are tender. ~ 9. Serve hot.", "6", "https://www.allrecipes.com/thmb/XkapTqFUR4U_fMMZQwgikkuoL-Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/RM-281995-ClassicHeartyBeefStew-ddmfs-3x4-6957-660344f4e4c8417fa6d1cf3175e0202c.jpg", "beef-and-vegetable-stew", "3", "Gluten-free", "Main Course"),
("Spicy black bean and corn salad", "Black Bean and Corn Salad", "This spicy black bean and corn salad is a refreshing side dish or light meal that's bursting with flavor. With black beans, sweet corn, and a tangy dressing, it's sure to be a hit!", "10", "0", "Black beans ~ Corn kernels ~ Red bell pepper ~ Red onion ~ Jalapeno pepper ~ Cilantro ~ Lime juice ~ Olive oil ~ Cumin ~ Chili powder ~ Salt ~ Black pepper", "1. In a large bowl, combine black beans, corn kernels, diced red bell pepper, diced red onion, minced jalapeno pepper, and chopped cilantro. ~ 2. In a small bowl, whisk together lime juice, olive oil, cumin, chili powder, salt, and black pepper. ~ 3. Pour dressing over bean mixture and toss to coat. ~ 4. Serve chilled or at room temperature.", "4", "https://www.eatingbirdfood.com/wp-content/uploads/2021/05/black-bean-and-corn-salad-hero-500x500.jpg", "black-bean-and-corn-salad", "2", "Vegetarian, Vegan, Gluten-free", "Side"),
("Flavorful vegetable stir-fry", "Vegetable Stir-Fry", "This flavorful vegetable stir-fry is a quick and easy dish that's perfect for busy weeknights. With a colorful array of vegetables and a savory sauce, it's both healthy and delicious!", "15", "15", "Broccoli florets ~ Bell peppers ~ Carrots ~ Snow peas ~ Mushrooms ~ Garlic ~ Ginger ~ Soy sauce ~ Sesame oil ~ Rice vinegar ~ Honey ~ Cornstarch ~ Green onions ~ Sesame seeds", "1. Heat sesame oil in a large skillet or wok over high heat. ~ 2. Add minced garlic and ginger, and stir-fry for 30 seconds. ~ 3. Add chopped vegetables and stir-fry until crisp-tender. ~ 4. In a small bowl, whisk together soy sauce, rice vinegar, honey, and cornstarch. ~ 5. Pour sauce over vegetables and toss to coat. ~ 6. Cook for an additional 2-3 minutes, until sauce has thickened. ~ 7. Garnish with sliced green onions and sesame seeds. ~ 8. Serve hot over rice or noodles.", "4", "https://cookieandkate.com/images/2017/03/spring-veggie-stir-fry.jpg", "vegetable-stir-fry", "4", "Vegetarian, Vegan", "Main Course"),
("Comforting chicken noodle soup", "Chicken Noodle Soup", "This comforting chicken noodle soup is a classic recipe that's perfect for sick days or chilly evenings. With tender chicken, hearty vegetables, and flavorful broth, it's sure to warm you up from the inside out!", "15", "30", "Chicken breast ~ Carrots ~ Celery ~ Onion ~ Garlic ~ Chicken broth ~ Egg noodles ~ Fresh parsley ~ Salt ~ Black pepper", "1. In a large pot, heat olive oil over medium heat. ~ 2. Add chopped onion, celery, and carrots. Cook until softened. ~ 3. Add minced garlic and cook until fragrant. ~ 4. Pour in chicken broth and bring to a simmer. ~ 5. Add diced chicken breast and cook until cooked through. ~ 6. Stir in cooked egg noodles. ~ 7. Season with salt, pepper, and chopped parsley. ~ 8. Serve hot.", "4", "https://hips.hearstapps.com/hmg-prod/images/chicken-noodle-soup-index-644c2bec1ce0c.jpg?crop=0.6666666666666666xw:1xh;center,top&resize=1200:*", "chicken-noodle-soup", "3", "", "Main Course"),
("Spicy beef tacos with salsa verde", "Spicy Beef Tacos", "These spicy beef tacos with salsa verde are a flavorful twist on traditional tacos. With seasoned ground beef, tangy salsa verde, and all the fixings, they're sure to be a hit at your next taco night!", "10", "20", "Ground beef ~ Taco seasoning ~ Corn tortillas ~ Salsa verde ~ Shredded lettuce ~ Diced tomatoes ~ Shredded cheese ~ Sour cream ~ Avocado", "1. In a large skillet, cook ground beef over medium heat until browned. ~ 2. Drain excess fat and stir in taco seasoning. ~ 3. Warm corn tortillas in a dry skillet or in the microwave. ~ 4. Fill tortillas with seasoned beef and top with salsa verde, shredded lettuce, diced tomatoes, shredded cheese, sour cream, and sliced avocado. ~ 5. Serve hot.", "4", "https://embed.widencdn.net/img/mccormick/iwej6mqwbx/840x840px/Quick%20and%20Easy%20Tacos_2019-05-30_TSUCALAS_%201716.jpg?crop=true&q=80&u=1zsthd", "spicy-beef-tacos", "2", "", "Main Course"),
("Creamy spinach and mushroom risotto", "Spinach and Mushroom Risotto", "This creamy spinach and mushroom risotto is a sophisticated dish that's perfect for a dinner party or date night. With creamy Arborio rice, sautéed mushrooms, and wilted spinach, it's sure to impress!", "20", "30", "Arborio rice ~ Mushrooms ~ Baby spinach ~ Shallots ~ Garlic ~ Vegetable broth ~ White wine ~ Parmesan cheese ~ Butter ~ Olive oil ~ Salt ~ Black pepper", "1. In a large skillet, heat olive oil over medium heat. ~ 2. Add chopped shallots and minced garlic. Cook until softened. ~ 3. Add sliced mushrooms and cook until golden brown. ~ 4. Stir in Arborio rice and cook for a few minutes. ~ 5. Deglaze the pan with white wine and cook until evaporated. ~ 6. Gradually add vegetable broth, stirring constantly, until rice is creamy and tender. ~ 7. Stir in baby spinach, Parmesan cheese, and butter. ~ 8. Season with salt and pepper. ~ 9. Serve hot, garnished with extra Parmesan cheese if desired.", "4", "https://img.taste.com.au/NdDFLPGL/taste/2016/11/mushroom-and-spinach-risotto-37376-1.jpeg", "spinach-and-mushroom-risotto", "5", "", "Main Course"),
("Easy homemade pizza with pepperoni", "Pepperoni Pizza", "This easy homemade pepperoni pizza is a classic favorite that's perfect for a fun family dinner. With a crispy crust, tangy tomato sauce, gooey cheese, and spicy pepperoni, it's sure to please everyone!", "20", "15", "Pizza dough ~ Tomato sauce ~ Mozzarella cheese ~ Pepperoni slices ~ Olive oil ~ Italian seasoning", "1. Preheat oven to 475°F (245°C). ~ 2. Roll out pizza dough on a floured surface and transfer to a greased baking sheet or pizza stone. ~ 3. Spread tomato sauce over dough, leaving a border around the edges. ~ 4. Sprinkle shredded mozzarella cheese over sauce. ~ 5. Arrange pepperoni slices on top of cheese. ~ 6. Drizzle with olive oil and sprinkle with Italian seasoning. ~ 7. Bake for 12-15 minutes, or until crust is golden brown and cheese is bubbly. ~ 8. Slice and serve hot.", "4", "https://i0.wp.com/www.womensweeklyfood.com.au/wp-content/uploads/sites/4/2022/03/18/28581/201802073421358325.jpg?fit=1456%2C1213&ssl=1", "pepperoni-pizza", "1", "", "Main Course"),
("Fresh and tangy Greek salad", "Greek Salad", "This fresh and tangy Greek salad is a light and refreshing side dish that's perfect for summer. With crisp cucumbers, juicy tomatoes, tangy feta cheese, and briny olives, it's a flavor explosion in every bite!", "10", "0", "Cucumbers ~ Tomatoes ~ Red onion ~ Kalamata olives ~ Feta cheese ~ Red wine vinegar ~ Olive oil ~ Dried oregano ~ Salt ~ Black pepper", "1. In a large bowl, combine sliced cucumbers, diced tomatoes, thinly sliced red onion, halved Kalamata olives, and crumbled feta cheese. ~ 2. In a small bowl, whisk together red wine vinegar, olive oil, dried oregano, salt, and black pepper. ~ 3. Pour dressing over salad and toss to coat. ~ 4. Serve chilled.", "4", "https://allthehealthythings.com/wp-content/uploads/2023/12/the-best-greek-salad-9.jpg", "greek-salad", "1", "Vegetarian, Gluten-free", "Side"),
("Rich and creamy chocolate mousse", "Chocolate Mousse", "This rich and creamy chocolate mousse is a decadent dessert that's perfect for special occasions. With just a few simple ingredients, it's surprisingly easy to make and oh so delicious!", "10", "120", "Dark chocolate ~ Heavy cream ~ Sugar ~ Vanilla extract ~ Eggs ~ Salt", "1. Melt chocolate in a heatproof bowl set over a pot of simmering water, stirring until smooth. ~ 2. In a separate bowl, whip heavy cream until soft peaks form. ~ 3. Gradually add sugar and vanilla extract, and continue to whip until stiff peaks form. ~ 4. In another bowl, beat egg yolks until pale and thick. ~ 5. Fold melted chocolate into whipped cream until well combined. ~ 6. Gently fold in beaten egg yolks. ~ 7. In a clean bowl, beat egg whites with salt until stiff peaks form. ~ 8. Fold egg whites into chocolate mixture until just combined. ~ 9. Divide mousse among serving dishes and refrigerate for at least 2 hours, or until set. ~ 10. Serve chilled, garnished with whipped cream and chocolate shavings if desired.", "4", "https://www.allrecipes.com/thmb/h1-rRJcI_8AMavPqqlBnwVIO3vA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/IMG_8145_Chocolate-Mousse-for-Beginners-4x3-cropped-757ae43035ff48cc8bc9ccffbd6cf3b7.jpg", "chocolate-mousse", "4", "", "Dessert"),
("Classic New York-style cheesecake", "New York Cheesecake", "This classic New York-style cheesecake is a rich and creamy dessert that's perfect for any occasion. With a buttery graham cracker crust and a smooth, tangy filling, it's sure to be a crowd-pleaser!", "20", "60", "Graham crackers ~ Butter ~ Cream cheese ~ Sugar ~ Eggs ~ Sour cream ~ Vanilla extract ~ Lemon zest", "1. Preheat oven to 325°F (160°C). ~ 2. Crush graham crackers into fine crumbs and mix with melted butter. Press mixture into the bottom of a springform pan. ~ 3. In a large bowl, beat cream cheese until smooth. ~ 4. Gradually add sugar and beat until light and fluffy. ~ 5. Beat in eggs one at a time, scraping down the sides of the bowl as needed. ~ 6. Stir in sour cream, vanilla extract, and lemon zest until well combined. ~ 7. Pour batter over crust and smooth the top. ~ 8. Bake for 55-60 minutes, or until center is set and edges are lightly golden. ~ 9. Turn off oven and let cheesecake cool in the oven with the door slightly ajar. ~ 10. Chill in the refrigerator for at least 4 hours before serving.", "6", "https://thescranline.com/wp-content/uploads/2023/05/NEW-YORK-STYLE-CHEESECAKE-S-01-500x500.jpg", "new-york-cheesecake", "4", "", "Dessert"),
("Refreshing cucumber mint mojito", "Cucumber Mint Mojito", "This refreshing cucumber mint mojito is a light and summery cocktail that's perfect for sipping on a hot day. With crisp cucumber, fragrant mint, and tangy lime, it's sure to cool you down!", "5", "0", "Cucumber ~ Fresh mint leaves ~ Lime ~ White rum ~ Simple syrup ~ Club soda ~ Ice", "1. In a cocktail shaker, muddle cucumber slices, mint leaves, and lime wedges. ~ 2. Add white rum and simple syrup. ~ 3. Fill shaker with ice and shake until well chilled. ~ 4. Strain mixture into a glass filled with ice. ~ 5. Top with club soda. ~ 6. Garnish with cucumber slices, mint sprigs, and a lime wheel. ~ 7. Serve immediately.", "1", "https://c6.staticflickr.com/9/8046/28998595061_edaa14558a_z.jpg", "cucumber-mint-mojito", "1", "", "Beverage, Alcoholic"),
("Creamy tomato basil soup", "Tomato Basil Soup", "This creamy tomato basil soup is a comforting classic that's perfect for a cozy night in. With ripe tomatoes, fragrant basil, and a touch of cream, it's like a warm hug in a bowl!", "10", "30", "Tomatoes ~ Onion ~ Garlic ~ Tomato paste ~ Vegetable broth ~ Heavy cream ~ Fresh basil ~ Butter ~ Salt ~ Black pepper", "1. In a large pot, melt butter over medium heat. ~ 2. Add chopped onion and minced garlic. Cook until softened. ~ 3. Add chopped tomatoes and tomato paste. Cook until tomatoes start to break down. ~ 4. Pour in vegetable broth and bring to a simmer. ~ 5. Use an immersion blender to puree the soup until smooth. ~ 6. Stir in heavy cream and chopped fresh basil. ~ 7. Season with salt and pepper to taste. ~ 8. Serve hot, garnished with extra basil leaves if desired.", "4", "https://www.superhealthykids.com/wp-content/uploads/2022/03/tomato-basil-soup-3-500x500.jpg", "tomato-basil-soup", "2", "", "Main Course, Side"),
("Spicy Thai green curry with tofu", "Thai Green Curry", "This spicy Thai green curry with tofu is a flavorful dish that's perfect for spice lovers. With creamy coconut milk, fragrant herbs, and a kick of heat, it's sure to tantalize your taste buds!", "15", "30", "Tofu ~ Thai green curry paste ~ Coconut milk ~ Bell peppers ~ Zucchini ~ Bamboo shoots ~ Fresh basil ~ Fish sauce ~ Brown sugar ~ Lime juice ~ Jasmine rice", "1. Press tofu to remove excess water, then cut into cubes. ~ 2. In a large skillet or wok, heat coconut milk over medium heat. ~ 3. Add Thai green curry paste and cook until fragrant. ~ 4. Add cubed tofu, sliced bell peppers, sliced zucchini, and bamboo shoots. ~ 5. Simmer until vegetables are tender and tofu is heated through. ~ 6. Stir in fresh basil, fish sauce, brown sugar, and lime juice. ~ 7. Serve hot over cooked jasmine rice.", "4", "https://www.deliciousmagazine.co.uk/wp-content/uploads/2020/01/thai-chicken-curry-768x960.jpg", "thai-green-curry", "4", "Vegetarian", "Main Course"),
("Flavorful beef and broccoli stir-fry", "Beef and Broccoli Stir-Fry", "This flavorful beef and broccoli stir-fry is a quick and easy dish that's perfect for busy weeknights. With tender beef, crisp broccoli, and a savory sauce, it's sure to become a family favorite!", "15", "15", "Flank steak ~ Broccoli florets ~ Garlic ~ Ginger ~ Soy sauce ~ Oyster sauce ~ Brown sugar ~ Cornstarch ~ Rice vinegar ~ Sesame oil ~ Red pepper flakes ~ Green onions ~ Cooked rice", "1. Thinly slice flank steak against the grain. ~ 2. In a small bowl, whisk together soy sauce, oyster sauce, brown sugar, cornstarch, rice vinegar, sesame oil, and red pepper flakes. ~ 3. In a large skillet or wok, heat oil over high heat. ~ 4. Add minced garlic and ginger, and cook until fragrant. ~ 5. Add sliced beef and cook until browned. ~ 6. Add broccoli florets and sauce mixture to the skillet. ~ 7. Stir-fry until broccoli is crisp-tender and sauce has thickened. ~ 8. Serve hot over cooked rice, garnished with sliced green onions.", "4", "https://omnivorescookbook.com/wp-content/uploads/2022/05/220503_Beef-And-Broccoli_550.jpg", "beef-and-broccoli-stir-fry", "4", "", "Main Course"),
("Creamy chicken Alfredo pasta", "Chicken Alfredo Pasta", "This creamy chicken Alfredo pasta is a comforting and indulgent dish that's perfect for a special occasion. With tender chicken, al dente pasta, and a rich Alfredo sauce, it's sure to impress!", "15", "20", "Chicken breast ~ Fettuccine pasta ~ Garlic ~ Heavy cream ~ Parmesan cheese ~ Butter ~ Olive oil ~ Salt ~ Black pepper ~ Fresh parsley", "1. Cook fettuccine pasta according to package instructions. ~ 2. Season chicken breast with salt and pepper. ~ 3. In a large skillet, heat olive oil over medium-high heat. ~ 4. Add minced garlic and cook until fragrant. ~ 5. Add chicken breast and cook until golden brown and cooked through. ~ 6. Remove chicken from skillet and set aside. ~ 7. In the same skillet, melt butter and whisk in heavy cream. ~ 8. Stir in grated Parmesan cheese until sauce is smooth and creamy. ~ 9. Slice cooked chicken and add it back to the skillet. ~ 10. Toss cooked pasta with Alfredo sauce until well coated. ~ 11. Serve hot, garnished with chopped fresh parsley.", "4", "https://rachaelsgoodeats.com/wp-content/uploads/2020/05/chickenalfredo.jpg", "chicken-alfredo-pasta", "3", "", "Main Course"),
("Refreshing watermelon feta salad", "Watermelon Feta Salad", "This refreshing watermelon feta salad is a light and summery dish that's perfect for picnics and barbecues. With juicy watermelon, tangy feta cheese, and fragrant mint, it's a flavor explosion in every bite!", "10", "0", "Watermelon cubes ~ Feta cheese ~ Red onion ~ Fresh mint leaves ~ Balsamic glaze ~ Olive oil ~ Salt ~ Black pepper", "1. In a large bowl, combine watermelon cubes, crumbled feta cheese, thinly sliced red onion, and torn mint leaves. ~ 2. Drizzle with balsamic glaze and olive oil. ~ 3. Season with salt and pepper to taste. ~ 4. Toss gently to combine. ~ 5. Serve chilled.", "4", "https://www.seriouseats.com/thmb/4q2pHbYsYhMXVHEdISs3u7IMTTo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210524-Watermelon-Feta-Mint-Salad-liz-voltz-seriouseats-4-cce131458da64fd2a5e64a4bf77def90.jpg", "watermelon-feta-salad", "2", "Vegetarian", "Side"),
("Flavorful chicken and vegetable kebabs", "Chicken and Vegetable Kebabs", "These flavorful chicken and vegetable kebabs are perfect for grilling season. With marinated chicken, colorful bell peppers, and sweet pineapple, they're a delicious and healthy option for your next barbecue!", "20", "15", "Chicken breast ~ Bell peppers ~ Red onion ~ Pineapple chunks ~ Olive oil ~ Garlic ~ Lemon juice ~ Soy sauce ~ Honey ~ Paprika ~ Salt ~ Black pepper", "1. Cut chicken breast into cubes and chop bell peppers and red onion into chunks. ~ 2. In a bowl, whisk together olive oil, minced garlic, lemon juice, soy sauce, honey, paprika, salt, and black pepper. ~ 3. Add chicken, bell peppers, red onion, and pineapple chunks to the bowl, and toss to coat in the marinade. ~ 4. Cover and refrigerate for at least 1 hour, or overnight. ~ 5. Thread marinated chicken and vegetables onto skewers. ~ 6. Preheat grill to medium-high heat. ~ 7. Grill kebabs for 10-15 minutes, turning occasionally, until chicken is cooked through and vegetables are tender. ~ 8. Serve hot.", "4", "https://www.freshoffthegrid.com/wp-content/uploads/grilled-chicken-and-veggie-kabobs-8-1-e1499102085621-1.jpg", "chicken-and-vegetable-kebabs", "3", "", "Main Course");
